### ISSUE TITLE
[CS12] chef-server-ctl upgrade from 11.0.12 to 12 fails - Failed to write fix to wait-for-rabbit script (contains how to fix on RC3)

### ISSUE THREAD

**Issue by gyoza** [chef/opscode-omnibus#463]
# chef-server-ctl upgrade
Upgrading with options #<OpenStruct skip_confirmation=false, chef11_server_url="https://localhost", chef12_server_url="https://localhost", upload_threads=10, chef11_admin_client_name="admin", chef11_admin_client_key="/etc/chef-server/admin.pem">
Open source Chef 11 server detected.
Would you like to upgrade? [yN]
y
Upgrading the open source Chef 11 server.
Chef 12 short organization name? x
Chef 12 full organization name? x
Creating /tmp/chef11-server-data20140908-23288-1j38cwo as the location to save the open source Chef 11 server data
Ensuring Chef 12 server is stopped
Failed to write fix to wait-for-rabbit script

**Comment by colby** [comment]
Just wanted to add to this a little bit. Save the `/tmp/chef11-server-data20150226-13190-13ark95/environments` bit from your error message, your path will be different.

Run `sudo chef-server-ctl chef12-upgrade-data-transform`, enter the same path as above. It will complete and spit out a new path with `chef12` in it.

Then run `sudo chef-server-ctl chef12-upgrade-upload`, enter the new path that the preview command gave you.

That should complete it. Thanks @mmzyk and @gyoza, this helped a lot. @josephrdsmith Any status on a fix from Chef, or at least word on this process?

**Comment by mmzyk** [comment]
I completely missed that @gyoza was plugging away figuring this out. At the moment the official Chef position is to only support upgrades from 11.1.0 (as if you're already on 11.0.x, it's not hard to upgrade to 11.1.0). However, if I get some time I'll look at seeing if we can incorporate the work that y'all (@gyoza, @colby) have done. No ETA on that though.

**Comment by colby** [comment]
Rad! Just wanna help who ever might be stuck in the same hole I was. :)

**Comment by colby** [comment]
Oh rad. Just wanna help who ever might be in the same hole I was.

**Comment by colby** [comment]
Or at the least, perhaps document the findings here, or make a note about needing to upgrade to one version before the other.

**Comment by mmzyk** [comment]
@colby We have tried to doc all over the place that you need to be on 11.1 to upgrade. Despite best efforts though, it still seems to get lost for a lot of people. I'll try to update the code when I can so then it doesn't matter.

**Comment by colby** [comment]
Ah man, I must have totally missed that. Perhaps super huge red font. 😎

Thanks though!

**Comment by stevendanna** [comment]
Hi @mmzyk @colby @gyoza.  I am in the process of moving all open issues from this repository to the chef-server repository.  In most cases I moved nearly the entire content of the ticket.  This ticket, however, contains a number of issues, so I opened a "Support upgrades from older 11.X versions" ticket here:

https://github.com/chef/chef-server/issues/182

with a link to this ticket.  While we don't currently have plans to support upgrades from arbitrary 11.X versions, that ticket will give the maintainers a place to state that clearly with an explanation during an upcoming triage meeting.

Thank you all for the work you put into this!  Please let me know if you have questions or concerns.
