### ISSUE TITLE
NGINX cert file not updated/does not match after Server 11->12 upgrade

### ISSUE THREAD

**Issue by tbunnyman** [chef/opscode-omnibus#465]
Upgrading Chef Server 11 to Chef Server 12RC2 changed the NGINX ssl certificate.

I had to delete the old one and pull a new one from the server. However pulling the file listed in knife's documents `/var/opt/chef-server/nginx/ca/HOSTNAME.crt` produced the old certificate that was no longer valid. I had to pull the certificate over https and using my web browser.

**Comment by stevendanna** [comment]
@tbunnyman Thank you for filing this issue.  We have recently merged our source-code repositories into a single chef-server repository.  As part of that merger, I moved your issue here:

https://github.com/chef/chef-server/issues/186

I've tried to capture the key facts and comments.  Thanks again!
