### ISSUE TITLE
OSC 11.1.4 - SUSE - error while run "chef-server-ctl reconfigure" 

### ISSUE THREAD

**Issue by weiqimeng** [chef/opscode-omnibus#516]
kernel info:
# uname -a
2.6.32.59-0.7-default #1 SMP 2012-07-13 15:50:56 +0200 x86_64 x86_64 x86_64 GNU/Linux

Recipe: chef-server::erchef
  * directory[/var/opt/chef-server/erchef] action create (up to date)
  * directory[/var/opt/chef-server/erchef/etc] action create (up to date)
  * directory[/var/log/chef-server/erchef] action create (up to date)
  * directory[/var/log/chef-server/erchef/sasl] action create (up to date)
  * link[/opt/chef-server/embedded/service/erchef/log] action create (up to date)
  * template[/opt/chef-server/embedded/service/erchef/bin/erchef] action create (up to date)
  * template[/var/opt/chef-server/erchef/etc/app.config] action create (up to date)
  * execute[remove_erchef_siz_files] action nothing (skipped due to action :nothing)
  * link[/opt/chef-server/embedded/service/erchef/etc/app.config] action create (up to date)
  * directory[/opt/chef-server/sv/erchef] action create (up to date)
  * directory[/opt/chef-server/sv/erchef/log] action create (up to date)
  * directory[/opt/chef-server/sv/erchef/log/main] action create (up to date)
  * template[/opt/chef-server/sv/erchef/run] action create (up to date)
  * template[/opt/chef-server/sv/erchef/log/run] action create (up to date)
  * file[/opt/chef-server/sv/erchef/down] action delete (up to date)
  * link[/opt/chef-server/init/erchef] action create (up to date)
  * link[/opt/chef-server/service/erchef] action create (up to date)
  * ruby_block[supervise_erchef_sleep] action run (skipped due to not_if)
  * service[erchef] action nothing (skipped due to action :nothing)
  * execute[/opt/chef-server/bin/chef-server-ctl start erchef] action run
    - execute /opt/chef-server/bin/chef-server-ctl start erchef

Recipe: chef-server::bootstrap
  * execute[verify-system-status] action run
================================================================================
Error executing action `run` on resource 'execute[verify-system-status]'
================================================================================

**Comment by stevendanna** [comment]
@weiqimeng Our apologies that you haven't seen a further response to this issue.  I am currently in the process of moving issues from this repository to your new, consolidated chef-server repository:

https://github.com/chef/chef-server

Rather than move this issue, I am going to recommend that if this is still a problem for you that you contact support@chef.io.  They can help identify the root cause and have a system in place to make sure that you get prompt responses.
