### ISSUE TITLE
Custom postgresql port is ignored

### ISSUE THREAD

**Issue by ares** [chef/opscode-omnibus#555]
https://github.com/opscode/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/providers/pg_database.rb#L21 does not honour custom port configured in chef-server.rb

Similar applies to `database_exist?` method below

**Comment by stevendanna** [comment]
As part of work to move into a consolidated repository, this ticket has been moved to:

https://github.com/chef/chef-server/issues/190

Thank you for taking the time to file it!
