### ISSUE TITLE
Installing add-ons on Amazon Linux fails

### ISSUE THREAD

**Issue by nathenharvey** [chef/opscode-omnibus#676]
The [add_ons_remote](https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/recipes/add_ons_remote.rb) recipe incorrectly sets the `major_version` when the recipe is run on Amazon Linux.

The [metadata.rb](https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/metadata.rb#l10-12) states that Amazon linux is supported.

**Comment by nathenharvey** [comment]
**Amazon Linux** 

    $ /opt/opscode/embedded/bin/ohai platform_family platform platform_version
    ffi-yajl/json_gem is deprecated, these monkeypatches will be dropped shortly
    [
      "rhel"
    ]
    [
      "amazon"
    ]
    [
      "2014.09"
    ]

**RHEL**

    $ /opt/opscode/embedded/bin/ohai platform_family platform platform_version
    ffi-yajl/json_gem is deprecated, these monkeypatches will be dropped shortly
    [
      "rhel"
    ]
    [
      "redhat"
    ]
    [
      "6.5"
    ]

**Comment by dpnl87** [comment]
During the installation a chef-stable.repo file is created with a baseurl: https://packagecloud.io/chef/stable/el/2014/$basearch This url does not exist and returns a 500 error.

As a monkey patch I've edited the ```major_version``` in the ```add_ons_remote.rb``` recipe to "6". This generates a baserepo that works: https://packagecloud.io/chef/stable/el/6/$basearch 

Stacktrace: https://gist.github.com/dpnl87/f5ab7f74c9394d918f32

**Comment by stevendanna** [comment]
As part of our work to consolidate into the chef-server repository.  As part of that work, this issue has been moved here:

https://github.com/chef/chef-server/issues/189

Thanks!
