### ISSUE TITLE
Migrate chef server 11 to a new instance with chef server 12

### ISSUE THREAD

**Issue by zjingbj** [chef/opscode-omnibus#687]
I have a instance with chef server version 11, and setup a new instance with chef server version 12 installed, I want to migrate chef data from the chef server 11 to the chef server 12.

I only find docs on in-place upgrade from version 11 to 12:
http://docs.getchef.com/server/upgrade_server.html#from-chef-server-osc
Is migrating from a chef server 11 to a new chef server 12 supported? and does there have any guide on chef migration?

I try to run upgrade subcommands on chef server 12 to do the migration, but this does not work. Following are my steps:
a. Copy the ssl certificate file from the chef server 11 to chef server 12, and ensure the ssl connection is OK.
>$ knife ssl check -c /tmp/knife-config.rb
Connecting to host cmwo35:14443
Successfully verified certificates from `cmwo35'

b. Copy the file "/etc/chef-server/admin.pem" from chef server 11 to chef server 12.
c. Run command "chef-server-ctl chef12-upgrade-download" to download everything from chef server 11. but failed with msg "knife download failed with pid 29862 exit 127"

>$ chef-server-ctl chef12-upgrade-download --chef11-data-dir /home/chef11 --chef11-server-url https://cmwo35:14443 --user admin --key /home/chef/admin.pem --download-only
the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same Ruby VM
falling back to ffi which might work (or might not, no promises)
Proceeding with options #<OpenStruct skip_setup=true, skip_download=false, skip_cleanup=true, chef11_server_url="https://cmwo35:14443", chef11_admin_client_name="admin", chef11_admin_client_key="/home/chef/admin.pem", chef11_data_dir="/home/chef11">
Preparing knife to download data from the open source Chef 11 server
Writing knife config to /tmp/knife-config.rb for use in downloading open source Chef 11 server data
Downloading data from the open source Chef 11 server
Running knife download
knife download failed with pid 29862 exit 127

d. Edit "/opt/opscode/embedded/service/omnibus-ctl/open_source_chef12_upgrade.rb" on chef server 12:
>Update 
    cmd = "/opt/chef-server/embedded/bin/knife download -c /tmp/knife-config.rb /"
to
    cmd = "/opt/chef/embedded/bin/knife download -c /tmp/knife-config.rb /"

e. Re-run command "chef-server-ctl chef12-upgrade-download", chef server 11 data(like environment, cookbooks, data bags...)could be downloaded now, but failed with another error msg "Failed to find /etc/chef-server/chef-server-running.json"

>$ chef-server-ctl chef12-upgrade-download --chef11-data-dir /home/chef11 --chef11-server-url https://cmwo35:14443 --user admin --key /home/chef/admin.pem --download-only
the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same Ruby VM
falling back to ffi which might work (or might not, no promises)
Proceeding with options #<OpenStruct skip_setup=true, skip_download=false, skip_cleanup=true, chef11_server_url="https://cmwo35:14443", chef11_admin_client_name="admin", chef11_admin_client_key="/home/chef/admin.pem", chef11_data_dir="/home/chef11">
Preparing knife to download data from the open source Chef 11 server
Writing knife config to /tmp/knife-config.rb for use in downloading open source Chef 11 server data
Downloading data from the open source Chef 11 server
Running knife download
Created /clients
Created /cookbooks
Created /data_bags
....
Created /cookbooks/yum-mysql-community-0.1.10/recipes/mysql55.rb
Pulling open source Chef 11 database credentials
Failed to find /etc/chef-server/chef-server-running.json

>$ ll /home/chef11
total 16
drwxr-xr-x.  2 root root   96 Feb  5 11:30 clients
drwxr-xr-x. 58 root root 4096 Feb  5 11:31 cookbooks
drwxr-xr-x.  7 root root 4096 Feb  5 11:30 data_bags
drwxr-xr-x.  2 root root 4096 Feb  5 11:30 environments
drwxr-xr-x.  2 root root   48 Feb  5 11:30 nodes
drwxr-xr-x.  2 root root 4096 Feb  5 11:30 roles
drwxr-xr-x.  2 root root   55 Feb  5 11:30 users

**Comment by mmzyk** [comment]
@zjingbj The upgrade steps as coded are intended for doing an in place upgrade; however there is a patch here https://github.com/chef/chef-server/issues/76#issuecomment-72447041 that might help you said, as it adds support for remote servers.

If you don't want to apply the patch, you can still migrate to a new server, but it takes a bit more work. In addition to the docs you found, there are docs with further details here: https://docs.chef.io/upgrade_server_open_source_notes.html

I see you've already found the individual commands. The basic steps you did are close to what you'll want to do. You'll want to use the upgrade command to download the data, then transform it, then move it to the new server (the data is stored in directories under tmp), then use the command to upload it to the new server.

For the most part, the commands should just work. Do not copy your admin.pem from Chef 11 to Chef 12. Chef 12 has a different permissions model and this is likely causing issues in what you attempted above. 

As far as the knife download failing on the Chef 11 server - what version of Chef 11 are you using? Upgrades only work on 11.1 and greater. If you are on an older version of Chef 11 you will need to upgrade to at least 11.1. I suspect this is the reason for the failure.

**Comment by zjingbj** [comment]
@mmzyk, thanks for your info, I still have some questions, please help.

1. Could you provide more info on "If you don't want to apply the patch, you can still migrate to a new server, but it takes a bit more work."?
Per my understanding, if I don't apply the patch, I will encounter error when  running command "chef-server-ctl chef12-upgrade-download".  because I don't have chef 11 installed on chef server 12, but I need to run command chef12-upgrade-download on chef server 12. The script for chef12-upgrade-download have so many paths which only exists on chef 11, like "/opt/chef-server/embedded/bin/knife", "/etc/chef-server/chef-server-running.json"...

2. When running command "chef-server-ctl chef12-upgrade-download" on chef server 12, a public key for option "--key" is required. so I copy the admin.pem from Chef server 11 to Chef server 12, and specify the file as option "--key". 
I am confused on "Do not copy your admin.pem from Chef 11 to Chef 12. ", if i don't copy the file to chef 12, how the specify --key?

3. to your question: my Chef 11 version is 11.12.8.

**Comment by mmzyk** [comment]
In order to not apply the patch, what you would do is install the chef-server-core package (the chef server 12 package) on your chef 11 box, but don't configure it or start it. This will give you access to the Chef 12 upgrade commands. You can then run chef12-upgrade-download on the Chef 11 box. Once you have the data, you can rsync or otherwise copy this data over to the chef 12 box and pick up the upgrade with the chef12-data-transform and chef12-upgrade-upload command. This is how you can do the command without applying the patch.

As far as the key, I misunderstood why you wanted to copy it. Yes, if you're using the patch you will need it in that one instance, so the upgrade command can talk to the Chef 11 server. Otherwise that key is not needed for anything in Chef 12. 

All the docs mention in place upgrades because that is the only path the tooling officially supports. However, we built flexibility into the tooling to allow for different paths of upgrading, which was the entire point of having the 3 separate commands. We will help you as much as we can in any path you take to upgrade, which is why the patch even exists, although it hasn't been merged in and released yet. That said, always ensure you have a backup of your data before upgrading.

As far as your chef version, that is your Chef client version. I was referring to your Chef server version. The upgrade process will only work with Chef 11 server version 11.1.0, 11.1.1, and 11.1.3. If you are not on one of those versions, you will have to upgrade to one of those first. You can look at which chef-server package you have installed on your system (the Chef 11 package is named chef-server, whereas the Chef 12 package is named chef-server-core)

**Comment by zjingbj** [comment]
@mmzyk, yes, 11.12.8 is my chef client version, my chef server version is 11.1.1. and according to your previous reply, this version would be ok.

Today I apply the pach and retry, get error message "PG::ConnectionBad: could not connect to server: No route to host".
 I am not sure if it is caused by usage error, please advise, thank you.

Values for the new added options on sql:
- ['chef_server']['postgresql']['vip']=127.0.0.1, so I specify the real ip address of chef server 11 as option --sql-host.(I have also try to use hostname "cmwo35", and get same error msg.)
- ['chef_server']['postgresql']['port']=5432, so I specify 5432 as option --sql-port
- ['chef_server']['postgresql']['sql_user']=opscode_chef, so I specify "opscode_chef" as option --sql-user
- ['chef_server']['postgresql']['sql_password']=17f007735ecdc546d6c456ff6f11ef0f62a0f6763b2693a9cc4ed40436074c54b93c795b8568f503d6874e6eb51ddca579a8, so I specify "17f007735ecdc546d6c456ff6f11ef0f62a0f6763b2693a9cc4ed40436074c54b93c795b8568f503d6874e6eb51ddca579a8" as option --sql-pass


Here are the detailed steps:
a. Pick the patch chef/opscode-omnibus#683 for chef server 12
b. Run cmd chef12-upgrade-download on chef server 12:
>[root@chefserver12 chef]# chef-server-ctl chef12-upgrade-download --chef11-data-dir /home/chef11 --chef11-server-url https://cmwo35:14443 --user admin --key /home/chef/admin.pem --download-only --sql-host 10.1.1.35 --sql-port 5432 --sql-user opscode_chef  --sql-pass 17f007735ecdc546d6c456ff6f11ef0f62a0f6763b2693a9cc4ed40436074c54b93c795b8568f503d6874e6eb51ddca579a8

>Proceeding with options #<OpenStruct skip_setup=true, skip_download=false, skip_cleanup=true, chef11_server_url="https://cmwo35:14443", chef11_admin_client_name="admin", chef11_admin_client_key="/home/chef/admin.pem", chef11_data_dir="/home/chef11", sql_host="10.1.1.35", sql_port=5432, sql_user="opscode_chef", sql_pass="17f007735ecdc546d6c456ff6f11ef0f62a0f6763b2693a9cc4ed40436074c54b93c795b8568f503d6874e6eb51ddca579a8">
Preparing knife to download data from the open source Chef 11 server
Writing knife config to /tmp/knife-config.rb for use in downloading open source Chef 11 server data
Downloading data from the open source Chef 11 server
Running knife download
knife download failed with pid 3572 exit 127

c. Edit "/opt/opscode/embedded/service/omnibus-ctl/open_source_chef12_upgrade.rb" on chef server 12:
>Update 
cmd = "/opt/chef-server/embedded/bin/knife download -c /tmp/knife-config.rb /"
to
cmd = "/opt/chef/embedded/bin/knife download -c /tmp/knife-config.rb /"

d. Re-run chef12-upgrade-download on chef server 12
>[root@chefserver12 chef]# chef-server-ctl chef12-upgrade-download --chef11-data-dir /home/chef11 --chef11-server-url https://cmwo35:14443 --user admin --key /home/chef/admin.pem --download-only --sql-host 10.1.1.35 --sql-port 5432 --sql-user opscode_chef  --sql-pass 17f007735ecdc546d6c456ff6f11ef0f62a0f6763b2693a9cc4ed40436074c54b93c795b8568f503d6874e6eb51ddca579a8

>Proceeding with options #<OpenStruct skip_setup=true, skip_download=false, skip_cleanup=true, chef11_server_url="https://cmwo35:14443", chef11_admin_client_name="admin", chef11_admin_client_key="/home/chef/admin.pem", chef11_data_dir="/home/chef11", sql_host="10.1.1.35", sql_port=5432, sql_user="opscode_chef", sql_pass="17f007735ecdc546d6c456ff6f11ef0f62a0f6763b2693a9cc4ed40436074c54b93c795b8568f503d6874e6eb51ddca579a8">
Preparing knife to download data from the open source Chef 11 server
Writing knife config to /tmp/knife-config.rb for use in downloading open source Chef 11 server data
Downloading data from the open source Chef 11 server
Running knife download
Created /clients
Created /cookbooks
...
Created /cookbooks/windows-1.30.0/resources/pagefile.rb
SQL configuration fully specified on the command line
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:217:in `initialize': PG::ConnectionBad: could not connect to server: No route to host (Sequel::DatabaseConnectionError)
        Is the server running on host "10.1.1.35" and accepting
        TCP/IP connections on port 5432?
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:217:in `new'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/postgres.rb:217:in `connect'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool.rb:96:in `make_new'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:158:in `make_new'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:137:in `available'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:127:in `block in acquire'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:194:in `block in sync'
        from <internal:prelude>:10:in `synchronize'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:194:in `sync'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:126:in `acquire'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/connection_pool/threaded.rb:94:in `hold'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/database/connecting.rb:250:in `synchronize'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/shared/postgres.rb:446:in `server_version'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/adapters/shared/postgres.rb:1563:in `server_version'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/sql.rb:228:in `select_sql'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:139:in `each'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:45:in `block in all'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:856:in `_all'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/sequel-4.13.0/lib/sequel/dataset/actions.rb:45:in `all'
        from (eval):398:in `create_chef11_key_file'
        from (eval):84:in `download_chef11_data_download'
        from (eval):60:in `download_chef11_data'
        from (eval):100:in `block (2 levels) in load_files'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/lib/omnibus-ctl.rb:177:in `call'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/lib/omnibus-ctl.rb:177:in `block in add_command_under_category'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/lib/omnibus-ctl.rb:555:in `run'
        from /opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/omnibus-ctl-0.3.1/bin/omnibus-ctl:31:in `<top (required)>'
        from /opt/opscode/embedded/bin/omnibus-ctl:23:in `load'
        from /opt/opscode/embedded/bin/omnibus-ctl:23:in `<main>'

e. my /etc/chef-server/chef-server-running.json on chef server 11 is below:
>"postgresql": {
      "enable": true,
      "ha": false,
      "dir": "/var/opt/chef-server/postgresql",
      "data_dir": "/var/opt/chef-server/postgresql/data",
      "log_directory": "/var/log/chef-server/postgresql",
      "svlogd_size": 1000000,
      "svlogd_num": 10,
      "username": "opscode-pgsql",
      "shell": "/bin/sh",
      "home": "/var/opt/chef-server/postgresql",
      "user_path": "/opt/chef-server/embedded/bin:/opt/chef-server/bin:$PATH",
      "sql_user": "opscode_chef",
      "sql_password": "17f007735ecdc546d6c456ff6f11ef0f62a0f6763b2693a9cc4ed40436074c54b93c795b8568f503d6874e6eb51ddca579a8",
      "sql_ro_user": "opscode_chef_ro",
      "sql_ro_password": "015be9a0fc9ab0634ddb5da1f8358562941e541865ede146df6dad0bb902dd7891a9a10d7345c3e399828090b858cdd4c598",
      "vip": "127.0.0.1",
      "port": 5432,
      "listen_address": "0.0.0.0",
      "max_connections": 200,
      "md5_auth_cidr_addresses": [
      ],
"trust_auth_cidr_addresses": [
        "127.0.0.1/32",
        "::1/128"
      ],
      "shmmax": 17179869184,
      "shmall": 4194304,
      "shared_buffers": "958MB",
      "work_mem": "8MB",
      "effective_cache_size": "1916MB",
      "checkpoint_segments": 10,
      "checkpoint_timeout": "5min",
      "checkpoint_completion_target": 0.9,
      "checkpoint_warning": "30s"
    }
  },

**Comment by stevendanna** [comment]
I think that the problem might be the value of the `-x` parameter in this command:

    chef-server-ctl chef12-upgrade-upload -e /home/chef12 -x https://chefserver12/organizations/ibm -o ibm

That is supposed to be the "root_url" so it should be "https://chefserver12/".  However, if you are on the Chef Server 12 machine, you can leave it off entirely.  The upload tool should ensure that your data makes it into the ibm organization based on the `-o` attribute.

**Comment by mmzyk** [comment]
Going to close this out, as I believe the issue here has been solved, based on no more feedback. Reopen if I'm wrong.

**Comment by zjingbj** [comment]
Thanks stevendanna for your help, I have completed the migration. but I still need to do following modification, otherwise, Command chef12-upgrade-download will fail with message "knife download failed with pid 3572 exit 127"

>Edit "/opt/opscode/embedded/service/omnibus-ctl/open_source_chef12_upgrade.rb" on chef server 12:
Update 
cmd = "/opt/chef-server/embedded/bin/knife download -c /tmp/knife-config.rb /"
to
cmd = "/opt/chef/embedded/bin/knife download -c /tmp/knife-config.rb /"

@mmzyk, @stevendanna, please help check, thank you.
