### ISSUE TITLE
Chef 12.0.x Failed Login With Ldap login_attribute Set non-lowercase

### ISSUE THREAD

**Issue by sean-horn** [chef/opscode-omnibus#694]
As a customer, I expect the typical casing of "sAMAccountName" to work when I provide it in `/etc/opscode/chef-server.rb` as

    ldap['login_attribute'] = "sAMAccountName"

However, eldap expects all lowercase for that attribute, as in https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/templates/default/oc_erchef.config.erb#L86

We should lowercase this as in https://github.com/chef/opscode-omnibus/pull/695

**Comment by stevendanna** [comment]
I believe this should be fixed here: 

https://github.com/chef/oc_erchef/blob/master/apps/oc_chef_wm/src/oc_chef_wm_authn_ldap.erl#L181-L183

which will be available in the next version of oc_erchef.  We'll close this out once that ships.

**Comment by sean-horn** [comment]
Yes, looks like it. Thanks, @stevendanna
