### ISSUE TITLE
Control RabbitMQ Memory Allocation

### ISSUE THREAD

**Issue by sean-horn** [chef/opscode-omnibus#701]
As a customer, I would like opscode-omnibus to offer control of the rabbitmq memory allocation in the config area with contents in /var/opt/opscode/drbd/data/rabbit/db/rabbit@localhost/etc/rabbitmq.config, like

    [ {rabbit, [{vm_memory_high_watermark, <%= node['private_chef']['rabbitmq']['mem'] %>}] } ].

**Comment by stevendanna** [comment]
@sean-horn I'm sure you have many of these messages in your inbox by now!  This issue, like the others have you filed (Thanks!) has been moved to the chef-server repository:

https://github.com/chef/chef-server/issues/187
