### ISSUE TITLE
FQDN longer than 64 characters result in unusable nginx installation on OPC

### ISSUE THREAD

**Issue by sean-horn** [chef/opscode-omnibus#715]
From http://tickets.chef.co/browse/OC-7334

Openssl will fail to create a certificate if the CN is longer than 64 characters. By default the CN of the certificate created by the private-chef-ctl reconfigure cookbooks is set to the `api_fqdn`.

The reconfigure will not fail but will instead create an empty certificate file. Nginx fails to start as it is unable to parse the empty certificate file correctly.

**Comment by stevendanna** [comment]
Thanks @sean-horn I've moved this here: https://github.com/chef/chef-server/issues/184
