### ISSUE TITLE
Change  to produce a desired RuntimeError message

### ISSUE THREAD

**Issue by kevindickerson** [chef/opscode-omnibus#723]
This `raise` [1] produces a RuntimeError message. The message is incorrect. The message has not been updated to reflect the new location for `chef-server.rb` for Chef 12.

**Incorrect**
The RuntimeError message directs users to look at `/etc/opscode/private-chef.rb`.

**Correct**
The RuntimeError message directs users to look at `/etc/opscode/chef-server.rb`.

**References**
1. https://github.com/chef/opscode-omnibus/blob/12.0.5/files/private-chef-cookbooks/private-chef/libraries/private_chef.rb#L390

**Comment by stevendanna** [comment]
@kevindickerson Thanks for filing this issue.  I have moved it to our chef-server repository here:

https://github.com/chef/chef-server/issues/183
