### ISSUE TITLE
Update jetty in solr to jetty 9

### ISSUE THREAD

**Issue by jessehu** [chef/opscode-omnibus#725]
As https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00069.html said "This year will mark the end of our open source support for Jetty 7 and Jetty 8." So Jetty 6/7/8 is end of life by 2014.

Can we update solr to newer version which uses higher version of jetty ? Chef Server 11 nows uses jetty 6.1.3.

ll /opt/chef-server/embedded/service/chef-solr/jetty/lib/total 740
-rw-r--r-- 1 root root 472383 Oct 17 01:50 jetty-6.1.3.jar
-rw-r--r-- 1 root root 128058 Oct 17 01:50 jetty-util-6.1.3.jar
drwxr-xr-x 2 root root   4096 Mar 12 03:09 jsp-2.1
-rw-r--r-- 1 root root 131998 Oct 17 01:50 servlet-api-2.5-6.1.3.jar

related code: https://github.com/chef/opscode-omnibus/blob/master/config/software/opscode-solr4.rb

 Our product uses Chef 11 and jetty 9.2.9 is required by the security strategry.

Thanks.

**Comment by jessehu** [comment]
Hi @stevendanna,  any plan for this ?

**Comment by stevendanna** [comment]
Hi @jessehu.  We recently started weekly triage meetings for the Chef Server and this was discussed in that meeting.  I've been assigned to look into what it will take for us to upgrade.  Once I find out what the situation is here, I'll have a better sense of what our ETA will be.

**Comment by jessehu** [comment]
Thanks a lot. Stay tuned.

**Comment by stevendanna** [comment]
It looks like the latest versions of solr4 and solr5 both use Jetty 8.  Thus, it looks like for us to move to Jetty 9 will require that we build and manage jetty ourselves. 

This isn't a deal-breaker, just putting a note here for informational purposes.

**Comment by jessehu** [comment]
Thanks a lot @stevendanna . Jetty 8 will be mucher better than jetty 6 for us to pass the security review.

**Comment by stevendanna** [comment]
@jessehu Thanks for the info about Jetty 8.  I've moved this here: https://github.com/chef/chef-server/issues/180 and will be testing upgrading solr early next week.
