### ISSUE TITLE
`cleanse` command doesn't delete the upstart file

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/opscode-omnibus#729]
The `chef-server-ctl cleanse` command in Chef Server 12 doesn't delete the upstart file because it's looking for `/etc/init/chef-server-runsvdir.conf` when the file is actually still named `/etc/init/private-chef-runsvdir.conf`.

https://github.com/chef/omnibus-ctl/blob/master/lib/omnibus-ctl.rb#L223

**Comment by stevendanna** [comment]
@jeremiahsnapp Thank you for the report.  This issue has been moved to the new chef-server repository: https://github.com/chef/chef-server/issues/179
