### ISSUE TITLE
Chef Server >= 12.0.4 Included omnibus-ctl Must Invoke Stateless chef-client Runs

### ISSUE THREAD

**Issue by sean-horn** [chef/opscode-omnibus#730]
As a customer, I need Chef Server's embedded cookbooks to be stateless, except for what is found in /etc/opscode https://github.com/chef/omnibus-ctl/issues/24 + https://github.com/chef/omnibus-ctl/pull/25

ZenDesk 3384

**Comment by docwhat** [comment]
Without this, things behave very odd from a customer point of view. Options that won't disappear , etc.

**Comment by docwhat** [comment]
@stevendanna are you rejecting this issue or was it close by accident?

**Comment by mmzyk** [comment]
@docwhat I believe this was closed because this has been fixed with https://github.com/chef/omnibus-ctl/pull/27 and should ship soon in a server release.

**Comment by docwhat** [comment]
Cool!
