### ISSUE TITLE
Chef server 12 should provide server port configurable

### ISSUE THREAD

**Issue by yinym** [chef/opscode-omnibus#732]
Back to Chef server 11, we can customize chef server port with writing following options to /etc/chef-server/chef-server.rb:
```
nginx['ssl_port']='9443'
```
For Chef server 12, we can do similar thing to /etc/opscode/chef-server.rb:
```
nginx['ssl_port']='9443'
```
After that, we run `chef-server-ctl reconfigure` to reconfigure Chef server. Now chef server can listen on port 9443, but there remains several configurations that still point to old Chef server url:

* /var/opt/opscode/oc-chef-pedant/etc/pedant_config.rb
```
chef_server "https://<chef-server-hostname>"
```
It is supposed to be
```
chef_server "https://<chef-server-hostname>:9443"
```
And this configuration will cause `chef-server-ctl test` failed to connect to new Chef server url
* /opt/opscode/embedded/service/opscode-erchef/etc/app.config
```
{s3_url, "https://<chef-server-hostname>"},
```
This will cause erchef failed to connect to bookshelf with connection refused error.
* /opt/opscode/embedded/service/opscode-chef-mover/etc/sys.config
```
{s3_url, "https://<chef-server-hostname>"},
```
Same issue as above, chef-mover won't be able to connect to bookshelf.

Fix needs to be added into private-chef cookbook to support customizing chef server port.

**Comment by yinym** [comment]
https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/templates/default/opscode-chef-mover.config.erb#L72
https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/templates/default/oc_erchef.config.erb#L163
Above 2 templates should contain the port for bookshelf

https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/libraries/private_chef.rb#L292
This library helper should also support customize port for nginx url.

**Comment by stevendanna** [comment]
@yinym This is definitely an issue.  I'm going to close out this ticket in favor of https://github.com/chef/chef-server/issues/50 which covers the same thing. Thanks!
